spring.application.name=mcp-client-example
spring.main.web-application-type=none
spring.threads.virtual.enabled=true
spring.ai.model.embedding=none
spring.ai.model.moderation=none
spring.ai.model.ocr=none
spring.ai.mcp.client.streamable-http.connections.pope-search-mcp-server.url=http://localhost:8080/mcp
spring.ai.mcp.client.streamable-http.connections.time-mcp-server.url=http://localhost:8081/mcp
spring.ai.mistralai.api-key=${MISTRAL_AI_API_KEY}
spring.ai.mistralai.base-url=https://api.eu.mistral.ai
spring.ai.mistralai.chat.model=mistral-medium-latest
spring.ai.mistralai.chat.temperature=0.1
spring.ai.retry.backoff.initial-interval=5s
spring.ai.retry.backoff.multiplier=2
spring.ai.retry.on-http-codes=429
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
