spring.application.name=rag-example
spring.main.web-application-type=none
spring.threads.virtual.enabled=true
spring.ai.model.moderation=none
spring.ai.model.ocr=none
spring.ai.vectorstore.qdrant.host=${QDRANT_HOST}
spring.ai.vectorstore.qdrant.use-tls=true
spring.ai.vectorstore.qdrant.api-key=${QDRANT_API_KEY}
spring.ai.vectorstore.qdrant.collection-name=popes
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.mistralai.api-key=${MISTRAL_AI_API_KEY}
spring.ai.mistralai.base-url=https://api.eu.mistral.ai
spring.ai.mistralai.chat.model=mistral-medium-latest
spring.ai.mistralai.chat.temperature=0.1
spring.ai.mistralai.embedding.model=mistral-embed
spring.ai.model.chat=mistral
spring.ai.model.embedding=mistral
spring.ai.retry.backoff.initial-interval=5s
spring.ai.retry.backoff.multiplier=2
spring.ai.retry.on-http-codes=429
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
