spring.application.name=chat-client-example
spring.main.web-application-type=none
spring.threads.virtual.enabled=true
spring.ai.model.embedding=none
spring.ai.model.moderation=none
spring.ai.model.ocr=none
spring.ai.mistralai.api-key=${MISTRAL_AI_API_KEY}
spring.ai.mistralai.base-url=https://api.eu.mistral.ai
spring.ai.mistralai.chat.model=mistral-medium-latest
spring.ai.mistralai.chat.reasoning-effort=high
spring.ai.mistralai.chat.temperature=0.1
spring.ai.model.chat=mistral
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
